### ISSUE TITLE
Revisar index.ts

### ISSUE THREAD

**Issue by japhernandez** [tsclean/scaffold#11]
Se debe de buscar la forma de solo actualizar el index.ts cuando se crea un adaptador para una base de datos si existe otro, esto quiere decir que se utilizarían dos base de datos en el proyecto, por esta razón borra el contenido del archivo y reescribe el contenido del template nuevo de acuerdo a la nueva base de datos

**Comment by tsclean** [comment]
Se da solución separando la responsabilidad del index.ts, esto se ha logrado al crear instancias singleton para el manejo de las conexiones de las bases de datos.
