### ISSUE TITLE
New project error

### ISSUE THREAD

**Issue by joaodezembro** [tsclean/scaffold#2]
When trying to run "scaffold create:project --name=[project name]" and the root path contains some folder with space, like "Personal Projects" the bash command returns error on "(...)/Personal". The bash command is ignoring the space in the folder name.

![image](https://user-images.githubusercontent.com/41813537/145101146-ee385eb9-853e-48d7-b77c-09825a5a141d.png)
Example: Folder name is "NoCode SaaS" and is read like "NoCode" only

**Comment by tsclean** [comment]
By package convention, project names must be in camel case or hyphen.
