### ISSUE TITLE
Not Working correctly

### ISSUE THREAD

**Issue by BarisZencir** [tsclean/scaffold#3]
Hi,

İ followed step by step this article. 
https://dev.to/japhernandez/clean-architecture-with-nodejs-typescript-and-mongo-3ene

But its not build project like it. 
For example, when i write "scaffold create:interface --name=add-user --path=models" this to console, its create contracts folder under the domain/modal, not gataway. And other methods not update index.js. Just creates ts. documents by empty classes. 

Scaffold project will be very useful. Liked it very much. I would be very grateful if you could help me with my problem.

Thanks.

**Comment by tsclean** [comment]
Indeed, a folder called contracts was created, this change was made to be more explicit in the process.

The whole project creates a .ts file and adds initial code for the development, the following post shows you the code that you must put in each of the files that the package generates.

You can write me on Twitter @JohnpiedrahitaH or on LinkedIn https://www.linkedin.com/in/john-piedrahita-30593a179/

Greetings.
