### ISSUE TITLE
camelCased names

### ISSUE THREAD

**Issue by marcosrocha85** [tsclean/scaffold#4]
We use camelCase for all directories and files at our company. I started to use scaffold for Clean Architecture services and I'm enjoying it a lot. But I missing a configuration for use camelCase in directory and file names. Can I create a pull request in order to achieve that?
I was wondering something like a option tag and a .tscleanrc to customize per-project parameters.

**Comment by japhernandez** [comment]
By convention in the project, all files and directories are named with lowercase letters and when they are two words they are separated by the hyphen, this helps to generate additional code in some of the tasks. As you can see in all the written code if you find CamelCase which is a standard of TypeScript.

If you need any additional help, do not hesitate to write to the following email: citymanager02@gmail.com

regards

**Comment by marcosrocha85** [comment]
Hello @japhernandez. Thank you for your response.
I started to use scaffold but I ended up by creating my own structure using NestJS and Clean Architecture. Of cource, I used most of concepts learned here, but at the end we made a path very far away from built solutions. Thank you for this amazing package and your support. Best wishes.
